server:
  port: 8004

spring:
  profiles:
    active: dev

  application:
    name: service-cms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/college_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

  #返回json的全局时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

mybatis-plus:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    #逻辑删除
    db-config:
      logic-delete-field: isDeleted #全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#开启熔断机制
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 设置hystrix超时时间，默认1000ms
            timeoutInMilliseconds: 6000
