server:
  port: 8003

spring:
  profiles:
    active: dev

  application:
    name: service-vod

  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

  #返回json的全局时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"

  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

#阿里云 vod
aliyun:
  vod:
    file:
      keyid: "8888888"
      keysecret: "88888888"


