server:
  port: 8002

spring:
  profiles:
    active: dev

  application:
    name: service-oss

  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

  #返回json的全局时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"

#阿里云 OSS
aliyun:
  oss:
    file:
      #不同的服务器，地址不同
      endpoint: "oss-cn-shenzhen.aliyuncs.com"
      keyid: "88888"
      keysecret: "888888888"
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: "bucketname"
